<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>org.peruntech</groupId>
	<artifactId>perun-assets</artifactId>
	<version>4.0.0-SNAPSHOT</version>
	<packaging>bundle</packaging>
	<name>perun-assets</name>
	<url>https://github.com/PerunTech/perun-assets</url>
	<organization>
		<name>Perun Technologies</name>
		<url>http://peruntech.org</url>
	</organization>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>
	<build>
		<resources>
			<resource>
				<directory>${project.basedir}</directory>
				<includes>
					<include>assets/**/*.*</include>
				</includes>
			</resource>
		</resources>
		<plugins>
		<plugin>
				<groupId>org.jreleaser</groupId>
				<artifactId>jreleaser-maven-plugin</artifactId>
				<version>1.19.0</version>
				<configuration>
					<jreleaser>
						<signing>
							<active>ALWAYS</active>
							<armored>true</armored>
						</signing>
						<deploy>
							<maven>
								<nexus2>
									<maven-central>
										<active>ALWAYS</active>
										<url>
											https://s01.oss.sonatype.org/service/local</url>
										<closeRepository>false</closeRepository>
										<releaseRepository>false</releaseRepository>
										<stagingRepositories>
											target/staging-deploy</stagingRepositories>
									</maven-central>
								</nexus2>
							</maven>
						</deploy>
					</jreleaser>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
				<version>3.1.0</version>
				<executions>
					<execution>
						<id>attach-sources</id>
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.5.1</version>
				<configuration>
					<source>1.7</source>
					<target>1.7</target>
				</configuration>
			</plugin>
			<!-- From here is the bundle configuration for the OSGI container -->
			<plugin>
				<groupId>org.apache.felix</groupId>
				<artifactId>maven-bundle-plugin</artifactId>
				<version>1.4.0</version>
				<extensions>true</extensions>
				<configuration>
					<instructions>
						<Bundle-SymbolicName>${pom.artifactId}</Bundle-SymbolicName>
						<Bundle-Name>Perun Assets</Bundle-Name>
						<Bundle-Vendor>Perun.Tech</Bundle-Vendor>
						<Bundle-Description>
							A bundle that provides assets for the Perun Core GUI
						</Bundle-Description>
						<Bundle-Activator>
							perun.perun_assets.Activator
						</Bundle-Activator>
						<Export-Package>
							perun.perun_assets
						</Export-Package>
						<Private-Package>
							com.prtech.triglav
						</Private-Package>
						<Import-Package>
							com.eclipsesource.jaxrs.publisher;version=!,*
						</Import-Package>
					</instructions>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<dependencies>
		<dependency>
			<groupId>org.apache.felix</groupId>
			<artifactId>org.osgi.core</artifactId>
			<version>1.0.0</version>
			<scope>provided</scope>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.osgi/org.osgi.service.http -->
		<dependency>
			<groupId>org.osgi</groupId>
			<artifactId>org.osgi.service.http</artifactId>
			<version>1.2.1</version>
			<scope>provided</scope>
		</dependency>
		<!-- https://mvnrepository.com/artifact/javax.ws.rs/jsr311-api -->
		<dependency>
			<groupId>svarog</groupId>
			<artifactId>svarog</artifactId>
			<version>[3.0.6,3.2.99]</version>
			<scope>provided</scope>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.glassfish.jersey.media/jersey-media-multipart -->
		<!-- https://mvnrepository.com/artifact/org.glassfish.jersey.core/jersey-server -->
		<dependency>
			<groupId>org.glassfish.jersey.core</groupId>
			<artifactId>jersey-server</artifactId>
			<version>2.22</version>
		</dependency>
		<dependency>
			<groupId>org.glassfish.jersey.media</groupId>
			<artifactId>jersey-media-multipart</artifactId>
			<version>2.22</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>servlet-api</artifactId>
			<version>2.4</version>
			<scope>provided</scope>
		</dependency>
	</dependencies>
</project>
